### ISSUE TITLE
[feature request] add source to quote data

### ISSUE THREAD

**Issue by hozza** [benhoneywill/stoic-quotes#23]
It would be great to add a source/reference to to the data and UI for further reading, i.e. where the quote came from etc.

I don't know how you compiled the `data/quotes.json` data but if it was done from another data set it might be trivial to add-in a source field also? If not, adding support for a source field would be a nice addition that others could contribute too.

e.g.

```
{
      "text": "Only the educated are free.",
      "author": "Epictetus"
      "source": "Discourses, Book II, ch. 1."
},
```

**Comment by benhoneywill** [comment]
Hey Hozza, I like the suggestion but unfortunately I don't have this data easily accessible. I'm always happy to accept contributions for Stoic Quotes if this is something you want to contribute yourself 😁
